# FORCAGE DU MODE UTF-8 POUR CONSOLE (OPTIONNEL SI NON NECESSAIRE)
CHCP 65001 > $NULL

# ENTETE DU SCRIPT
CLEAR-HOST
WRITE-HOST "==================================================" -FOREGROUNDCOLOR CYAN
WRITE-HOST "MIGRATION D'EDITION DE WINDOWS 11" -FOREGROUNDCOLOR CYAN
WRITE-HOST "==================================================" -FOREGROUNDCOLOR CYAN
WRITE-HOST ""
WRITE-HOST "CE SCRIPT PERMET DE PASSER D'UNE EDITION A UNE AUTRE" -FOREGROUNDCOLOR YELLOW
WRITE-HOST "EXEMPLES : FAMILLE -> PRO / FAMILLE -> EDUCATION N / PRO -> PRO N" -FOREGROUNDCOLOR YELLOW
WRITE-HOST ""
WRITE-HOST "ATTENTION : POUR CONSERVER VOS DONNEES, VOUS DEVEZ UTILISER UN ISO MULTI-EDITION" -FOREGROUNDCOLOR RED
WRITE-HOST ""

# INSTRUCTIONS POUR TELECHARGER L'ISO
WRITE-HOST "==================================================" -FOREGROUNDCOLOR DARKCYAN
WRITE-HOST "AVANT DE CONTINUER, TELECHARGEZ L'IMAGE DISQUE WINDOWS 11" -FOREGROUNDCOLOR DARKCYAN
WRITE-HOST "==================================================" -FOREGROUNDCOLOR DARKCYAN
WRITE-HOST ""
WRITE-HOST "1 - RENDEZ-VOUS SUR : HTTPS://WWW.MICROSOFT.COM/SOFTWARE-DOWNLOAD/WINDOWS11" -FOREGROUNDCOLOR GRAY
WRITE-HOST "2 - DESCENDEZ JUSQU'A 'TELECHARGER L'IMAGE DISQUE (ISO) WINDOWS 11'" -FOREGROUNDCOLOR GRAY
WRITE-HOST "3 - CHOISISSEZ : 'WINDOWS 11 (MULTI-EDITION ISO) POUR LES APPAREILS X64'" -FOREGROUNDCOLOR GRAY
WRITE-HOST "4 - SELECTIONNEZ LA LANGUE SOUHAITEE" -FOREGROUNDCOLOR GRAY
WRITE-HOST "5 - CLIQUEZ SUR 'TELECHARGER' ET ENREGISTREZ LE FICHIER ISO" -FOREGROUNDCOLOR GRAY
WRITE-HOST ""
WRITE-HOST "ENTREZ LE CHEMIN COMPLET VERS L'ISO WINDOWS 11 (EXEMPLE : C:\ISOS\WIN11.ISO)" -FOREGROUNDCOLOR GREEN
PAUSE

# MENU DES EDITIONS
CLEAR-HOST
WRITE-HOST "==================================================" -FOREGROUNDCOLOR CYAN
WRITE-HOST "CHOISISSEZ L'EDITION CIBLE POUR LA MIGRATION" -FOREGROUNDCOLOR CYAN
WRITE-HOST "==================================================" -FOREGROUNDCOLOR CYAN
WRITE-HOST ""
WRITE-HOST "1 - WINDOWS 11 FAMILLE"
WRITE-HOST "2 - WINDOWS 11 PRO"
WRITE-HOST "3 - WINDOWS 11 EDUCATION"
WRITE-HOST "4 - WINDOWS 11 FAMILLE N"
WRITE-HOST "5 - WINDOWS 11 PRO N"
WRITE-HOST "6 - WINDOWS 11 EDUCATION N"
WRITE-HOST ""

$CHOIX = READ-HOST "ENTREZ LE NUMERO CORRESPONDANT A L'EDITION"

SWITCH ($CHOIX) {
    "1" {
        $EDITIONID = "Core"
        $PRODUCTNAME = "Windows 11 Home"
    }
    "2" {
        $EDITIONID = "Professional"
        $PRODUCTNAME = "Windows 11 Pro"
    }
    "3" {
        $EDITIONID = "Education"
        $PRODUCTNAME = "Windows 11 Education"
    }
    "4" {
        $EDITIONID = "CoreN"
        $PRODUCTNAME = "Windows 11 Home N"
    }
    "5" {
        $EDITIONID = "ProfessionalN"
        $PRODUCTNAME = "Windows 11 Pro N"
    }
    "6" {
        $EDITIONID = "EducationN"
        $PRODUCTNAME = "Windows 11 Education N"
    }
    DEFAULT {
        WRITE-HOST "CHOIX INVALIDE. SCRIPT ANNULE." -FOREGROUNDCOLOR RED
        EXIT
    }
}

# CONFIRMATION
WRITE-HOST ""
WRITE-HOST "EDITION SELECTIONNEE : $PRODUCTNAME" -FOREGROUNDCOLOR GREEN
WRITE-HOST "LE REGISTRE VA ETRE MODIFIE POUR PERMETTRE LA MISE A NIVEAU." -FOREGROUNDCOLOR YELLOW
PAUSE

# MODIFICATION DU REGISTRE
SET-ITEMPROPERTY -PATH "HKLM:\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION" -NAME "EditionID" -VALUE $EDITIONID
SET-ITEMPROPERTY -PATH "HKLM:\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION" -NAME "ProductName" -VALUE $PRODUCTNAME
WRITE-HOST "REGISTRE MODIFIE AVEC SUCCES." -FOREGROUNDCOLOR GREEN

# DEMANDE DU CHEMIN VERS L'ISO
WRITE-HOST ""
WRITE-HOST "ENTREZ LE CHEMIN COMPLET VERS L'ISO WINDOWS (EX: C:\ISOS\WIN11.ISO)" -FOREGROUNDCOLOR GREEN
$ISOPATH = READ-HOST

# MONTAGE DE L'ISO
MOUNT-DISKIMAGE -IMAGEPATH $ISOPATH
START-SLEEP -SECONDS 2

# DETECTION DE LA LETTRE DU LECTEUR ISO
$DISK = GET-VOLUME | WHERE-OBJECT { $_.FILESYSTEMLABEL -LIKE "*CCCOMA*" -OR $_.DRIVETYPE -EQ "CD-ROM" }
IF ($DISK -EQ $NULL) {
    WRITE-HOST "LECTEUR ISO NON DETECTE. ASSUREZ-VOUS QUE L'ISO EST MONTE." -FOREGROUNDCOLOR RED
    EXIT
}

# EXECUTION DE L'INSTALLATEUR
$SETUPPATH = "$($DISK.DRIVELETTER):\SETUP.EXE"
WRITE-HOST "LANCEMENT DE L'INSTALLATEUR WINDOWS..." -FOREGROUNDCOLOR YELLOW
START-PROCESS -FILEPATH $SETUPPATH

# MESSAGE FINAL
WRITE-HOST ""
WRITE-HOST "MIGRATION DEMARREE ! N'OUBLIEZ PAS D'ENTRER VOTRE CLE D'ACTIVATION A LA FIN DE L'INSTALLATION." -FOREGROUNDCOLOR GREEN
